Make SecW-socket path configurable
42ity/fty-certificate-generator pull request #26
Opened 2020-03-30 12:42 UTC by jimklimov

Sister PR to https://github.com/42ity/fty-security-wallet/pull/49 (and https://github.com/42ity/fty-security-wallet/pull/51 that followed), using similarly defined configure-time definition of default shared socket file path.

This PR also adds actually parsing a config file so the template-defined value would get used (keeping so far the hardcoded strings for defaults).

2020-03-30 13:04 UTC, perrettecl requested changes
Reject to merge, This should be solve by the PR of Arnaud.

2020-03-30 13:39 UTC, jimklimov commented
The PR of Arnaud is on one hand a raw PoC that we are fixing, on another it is a platform-dependent hack (in the sense it is unusable and uncompilable as is on systems without systemd). The codebase state in both components as currently present hardcodes paths to files, definition of which is a prerogative of packaging.

2020-03-30 15:21 UTC, jimklimov commented
Marked as DNMY as the agent-side code (or rather config class family) needs more love to accept configurable socket path in case we manipulate "secw" store type. Hopefully as of now the PR HEAD state would not be harmful, falling back to the default hardcoded value, but lacking the actual injection of optionally configured socket-path value it is so far a big glorified no-op :(

2020-03-30 18:01 UTC, jimklimov commented
After discussion with Mauro, had some more ideas to try imposing the socket path into loaded configs while we load them. Implemented two of them, either can be enabled by an `ifdef` (currently both are, so the latter should override the former):
* patch in-memory JSON of the loaded config, if it is for a secw storage type and contains the expected JSON-structure path up to, but not including, a `secw_socket_path` string among `storage_params{}`.
* patch StorageConfig object that appears after config parsing, by a setter method in its class, but using a non-const reference during dynamic re-casting.

2020-04-03 08:33 UTC, stark-dev approved these changes

2020-04-03 16:49 UTC, jimklimov commented
At this point, this should work (equivalent code tested in feature image) including support of the config file honored during service restart.

2020-04-03 17:05 UTC, jimklimov commented
Testing-wise, it seems that when the second solution option is enabled, we either have a valid socket path from config file, or hardcoded defaults, and impose it into the run-time config object. This works, and specified socket path is used (or certgen crashes with invalid connection to non-existent path).

Due to this I could not really check with the binary I have in the OS image whether hot-fixing the deserialized JSON representation in memory works, as the results are always overwritten by the second solution :)

2020-04-08 10:48 UTC, jimklimov commented
Part of featureimage/systemd-deps product

2020-04-08 10:48 UTC, merged