Certificate server
42ity/fty-certificate-generator pull request #5
Opened 2019-11-04 07:31 UTC by jana-rapava

2019-11-04 08:28 UTC, perrettecl requested changes
Project.xml need to be updated

2019-11-04 08:28 UTC, perrettecl commented on src/certgen_certificate_config.cc
> +    std::string configFilePath (SELFTEST_DIR_RO + std::string ("certificate.config"));
Test need to be performed with at least one file well formed and one file formed correctly (positive vs negative tests)

2019-11-04 08:28 UTC, perrettecl commented on src/certgen_certificate_generator_server.cc
> +        m_supportedCommands[GENERATE_SELFSIGNED_CERTIFICATE] = std::bind(&CertificateGeneratorServer::handleGenerateSelfsignedCertificate, this, _1, _2);
Sender is not going to be necessary

2019-11-04 08:28 UTC, perrettecl commented on src/certgen_certificate_generator_server.cc
> +    std::string CertificateGeneratorServer::handleGenerateSelfsignedCertificate(const fty::Sender & /*sender*/, const fty::Payload & /*params*/)
Sender is not going to be necessary, we can remove it from the function

2019-11-05 12:55 UTC, stark-dev approved these changes

2019-11-08 09:49 UTC, merged